### ISSUE TITLE
Fix collisions with wall

### ISSUE THREAD

**Issue by azenagui** [JosselinSomervilleRoberts/AA228-Project-Autonomous-Vehicle#1]
At the moment we consider the middle of the car for the collision while we should be using a bounding box.
You can see the problem on the picture below.

![image](https://user-images.githubusercontent.com/123434720/221747235-5ff43437-6285-4e51-8b4b-d67e66d1acb8.png)

**Comment by JosselinSomervilleRoberts** [comment]
Solved with PR #2
